// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    var addToSimonArray, checkChoice, clickCounter, endGame, flashButton, flashSimon, levelCounter, newLevel, resetGame, runLevel, simonArray, userArray;
    simonArray = [];
    userArray = [];
    clickCounter = 0;
    levelCounter = 1;
    addToSimonArray = function() {
      var max, min, x;
      min = 0;
      max = 3;
      x = Math.floor(Math.random() * (max - min + 1)) + min;
      return simonArray.push(x);
    };
    resetGame = function() {
      simonArray = [];
      userArray = [];
      clickCounter = 0;
      levelCounter = 1;
      return addToSimonArray();
    };
    endGame = function() {
      console.log("Game Over");
      return resetGame();
    };
    checkChoice = function(userArray, simonArray) {
      console.log("User Array: " + userArray);
      console.log("Simon Array: " + simonArray);
      console.log("click counter: " + clickCounter);
      console.log("Level: " + levelCounter);
      if (userArray[clickCounter] === simonArray[clickCounter] && userArray.length === simonArray.length) {
        return newLevel();
      } else if (userArray[clickCounter] === simonArray[clickCounter]) {
        console.log("Correct Click");
        return clickCounter++;
      } else {
        return endGame();
      }
    };
    flashButton = function(i) {
      if (i === 0) {
        $("#button-0").removeClass('green').delay(50).queue(function(next) {
          $(this).addClass('green');
          return next();
        });
        return $("#button-0").addClass('greenFlash').delay(50).queue(function(next) {
          $(this).removeClass('greenFlash');
          return next();
        });
      } else if (i === 1) {
        $("#button-1").removeClass('yellow').delay(50).queue(function(next) {
          $(this).addClass('yellow');
          return next();
        });
        return $("#button-1").addClass('yellowFlash').delay(50).queue(function(next) {
          $(this).removeClass('yellowFlash');
          return next();
        });
      } else if (i === 2) {
        $("#button-2").removeClass('red').delay(50).queue(function(next) {
          $(this).addClass('red');
          return next();
        });
        return $("#button-2").addClass('redFlash').delay(50).queue(function(next) {
          $(this).removeClass('redFlash');
          return next();
        });
      } else {
        $("#button-3").removeClass('blue').delay(50).queue(function(next) {
          $(this).addClass('blue');
          return next();
        });
        return $("#button-3").addClass('blueFlash').delay(50).queue(function(next) {
          $(this).removeClass('blueFlash');
          return next();
        });
      }
    };
    flashSimon = function(simonArray) {
      var delay, i, max, run;
      i = 0;
      max = simonArray.length - 1;
      delay = 1000;
      run = function() {
        if (simonArray[i] === 0) {
          $("#button-0").removeClass('green').delay(500).queue(function(next) {
            $(this).addClass('green');
            return next();
          });
          $("#button-0").addClass('greenFlash').delay(500).queue(function(next) {
            $(this).removeClass('greenFlash');
            return next();
          });
        } else if (simonArray[i] === 1) {
          $("#button-1").removeClass('yellow').delay(500).queue(function(next) {
            $(this).addClass('yellow');
            return next();
          });
          $("#button-1").addClass('yellowFlash').delay(500).queue(function(next) {
            $(this).removeClass('yellowFlash');
            return next();
          });
        } else if (simonArray[i] === 2) {
          $("#button-2").removeClass('red').delay(500).queue(function(next) {
            $(this).addClass('red');
            return next();
          });
          $("#button-2").addClass('redFlash').delay(500).queue(function(next) {
            $(this).removeClass('redFlash');
            return next();
          });
        } else {
          $("#button-3").removeClass('blue').delay(500).queue(function(next) {
            $(this).addClass('blue');
            return next();
          });
          $("#button-3").addClass('blueFlash').delay(500).queue(function(next) {
            $(this).removeClass('blueFlash');
            return next();
          });
        }
        if (i++ < max) {
          return setTimeout(run, delay);
        }
      };
      run();
      return false;
    };
    newLevel = function() {
      levelCounter++;
      $(".level-counter").text(levelCounter);
      userArray = [];
      clickCounter = 0;
      addToSimonArray();
      flashSimon(simonArray);
      console.log("Won Level!");
      console.log("User Array: " + userArray);
      console.log("Simon Array: " + simonArray);
      console.log("click counter: " + clickCounter);
      return console.log("Level: " + levelCounter);
    };
    runLevel = function() {
      console.log("Waiting for click");
      flashSimon(simonArray);
      return $(".game-button").on("click", function(e) {
        var choice;
        choice = parseInt($(this).data('index'));
        flashButton(choice);
        userArray.push(choice);
        return checkChoice(userArray, simonArray);
      });
    };
    return $('#start-game').on('click', function(e) {
      resetGame();
      $(".level-counter").text(levelCounter);
      $(this).hide();
      return runLevel();
    });
  });

}).call(this);

//# sourceMappingURL=app.map
